### ISSUE TITLE
Classes and Properties Missing

### ISSUE THREAD

**Issue by fernanev** [DOREMUS-ANR/doremus-ontology#1]
Bonjour @pierrechoffe ,

I have seen that some classes and properties are missing. I don't know if that is because they are not verified yet.

Classes:
- M9_Derivation_Type
- M36_Performer_Type
- M37_Cast_Performer

Properties:
- U30_created_track
- U33_has_intended_performer
- U34_has_performer_type

Are you using the document "Nouvelles Classes & Properties.xlsx" for building the ontology? Maybe I am checking an old version.

**Comment by pierrechoffe** [comment]
Hi Eva,Thank you for this. I am presently in a meeting with Marie, so to answer quickly :M9 and U30 must be added, I will do this tomorrow :)As for the performed related classes and properties, I did not include them because CRM-SIG were very interested in the subject and would like to be part of the modelisation which is still a work in progress. This is a tricky one, basically the idea is to modelise the intension of the composer as to how many performers should be performing one medium of performance. So, since we do not have a clear solution yet, we cannot include these classes and properties in the model.I will check the version of new classes and properties but I think it is the right one.Thanks !PierreLe 3 mai 2016 à 10:10, Eva Fernández <notifications@github.com> a écrit :Bonjour @pierrechoffe ,I have seen that some classes and properties are missing. I don't know if that is because they are not verified yet.Classes:


M9_Derivation_Type
M36_Performer_Type
M37_Cast_Performer
Properties:


U30_created_track
U33_has_intended_performer
U34_has_performer_type
Are you using the document "Nouvelles Classes & Properties.xlsx" for building the ontology? Maybe I am checking an old version.—You are receiving this because you were mentioned.Reply to this email directly or view it on GitHub

**Comment by pierrechoffe** [comment]
Hi Eva,

Thank you for this. I am presently in a meeting with Marie, so to answer quickly :

M9 and U30 must be added, I will do this tomorrow :)

As for the performed related classes and properties, I did not include them because CRM-SIG were very interested in the subject and would like to be part of the modelisation which is still a work in progress. 

This is a tricky one, basically the idea is to modelise the intension of the composer as to how many performers should be performing one medium of performance. So, since we do not have a clear solution yet, we cannot include these classes and properties in the model.

I will check the version of new classes and properties but I think it is the right one.

Thanks !
Pierre

**Comment by pierrechoffe** [comment]
@fernanev 
I just added M9 and U30. The reason they were not added in the first place was that U30 had not been discussed in the modelisation wg yet ; regarding M9, this raises an interesting question which I wanted to address before adding the class in Protégé : 
M9 Derivation Type is the range of R2.1 has type which is a property of R2 is derivative of.
These properties of properties are listed in the owl description (see e.g. P14 and P14.1) but they do not have a description for themselves. How are they treated ? If I understand it right, the typed property has to be reified, how would this be modelled in Protégé ?
All best, Pierre

**Comment by pasqLisena** [comment]
Hi Pierre, your question is correct, but I am afraid that we will not have an answer so easily.

We found this [FRBRoo document](http://library.ifla.org/1150/1/207-leboeuf-en.pdf) in which they explicitely declare that it is impossible to write that properties in a RDF-compliant way (read paragraph 1.6).

For now I suggest to treat them just as FRBRoo do, so declare them in a comment, in this way

```rdf
<owl:ObjectProperty rdf:about="http://erlangen-crm.org/efrbroo/R2_is_derivative_of">
     ... 
     <rdfs:comment>
        Examples:
        William Schuman’s orchestration of Charles Ives’s ‘Variations on America’ (F15) R2 is derivative of Charles Ives’s ‘Variations on America’ (F15) R2.1 has type orchestration (E55)
        Charles Ives’s musical work entitled ‘Variations on America’ (F15) R2 is derivative of the musical work titled ‘America’ (F15) R2.1 has type variations (E55)
        The musical work entitled ‘America’ (F15) R2 is derivative of the musical work entitled ‘God save the King’ (F15) R2.1 has type same tune with different lyrics (E55)
        Properties:R2.1 has type: E55 Type
   </rdfs:comment>
   ....
</owl:ObjectProperty >
```

**Comment by pierrechoffe** [comment]
Hi Eva,

but how they dealt with in CRM ? the Cidoc-CRM ontology has lots of them
(e.g. P14 carried out by P14.1 in the role of) . Maybe it is not to be
detailed in the ontology but only in the implementation, is this what you
mean ?

p

2016-05-04 16:42 GMT+02:00 Pasquale Lisena <notifications@github.com>:
