### ISSUE TITLE
How multiple or alternate casting should be modeled?

### ISSUE THREAD

**Issue by pasqLisena** [DOREMUS-ANR/doremus-ontology#12]
Currently we have the `U25_alternate_casting` symmetric property for connecting two castings.

Questions:
1. Can we say that there is an "official" casting and an alternate one? If yes, how can we distinguish the two in the data that needs to be converted in RDF?
2. Is U25 not redundant? The two casting are in fact connected to the same expression.

<img width="886" alt="schermata 2016-08-25 alle 18 46 19" src="https://cloud.githubusercontent.com/assets/4126222/17978008/47893a62-6af4-11e6-8dc1-336aba386645.png">

**Comment by rtroncy** [comment]
I have edited @pasqLisena original issue description to make it slightly clearer. There are indeed two sub-questions:
* Can we really distinguish between multiple castings the role they supposedly have between ```main``` and ```alternate```? I meant, from the original MARC data!
* If this distinction matters, then adding a symmetric property named "alternate casting" between the two is obviously a bad modeling decision. How will you be able to query to get only an alternate casting? If we really want to make the distinction and we are sure we can materialize it from the data, then sub-classing M6 would be more appropriate

**Comment by pierrechoffe** [comment]
@pasqLisena @rtroncy before answering the questions, let's see the big picture : 

A piece of music can be written for piano but other versions may exist, either by the same composer or by other composers.
In the case of other composers, we are talking about derivative works, so this is another story.
Now, in the case of various versions of a composition by the same composer, there are 2 possibilities : 
(1) the composer decided that he would give a specific opus number to each. In this case, there are 2 different F22_Self_Contained_Expression and only one M6_casting. We treat these cases as if they were 2 different works, but we may add a relation between them (e.g. the F28_Expression_Creation of the 2nd F22 p16_used_specific_object the first F22).
(2) the composer did not indicate any specific opus number to each version. The piece is clearly written for (casting 1) *or* (casting 2), for example a piece "for 2 pianos or 4-hand piano"

Let's come back to your questions : 

>Can we really distinguish between multiple castings the role they supposedly have between main and alternate? I meant, from the original MARC data!

Since we are in case nr 2, there is clearly no main or alternate casting. They were born equal. So the property should be symmetric.

>If this distinction matters, then adding a symmetric property named "alternate casting" between the two is obviously a bad modeling decision.

The distinction does not matter. And to be clear, the notion of alternate casting only exists in case nr 2. The property is not relevant in any other case, because the semantics would be modeled differently (e.g. using F28 p16 F22).

**Comment by pasqLisena** [comment]
Thanks @pierrechoffe, for sure doubt n.1 is solved (all castings have the same importance). And yes, as you say, we should only consider castings declared by the same composer, if not we fall in the derivation case.

Given that, I try to reformulate the n.2. We have this two facts:
- the presence of 2 castings on the same expression;
- a U25 property connecting the two.

Which information U25 add respect to the first fact? I am just pointing out that we should evaluate if keep or remove U25.

**Comment by rtroncy** [comment]
Thanks @pierrechoffe for clearly explaining what multiple castings means, and indeed, let's see in other issues how we will model relationships between works (and expressions). The reformulation of @pasqLisena is correct: given what you're saying, the bare existence of u25 is completely useless. The *alternate* casting exists already by the virtue of having more than one occurrence of u13 attached to the F22. Adding a u25 adds nothing but confusion, since it gives dominance to one particular casting over the other which is exactly what you want to avoid.

Proposal: remove u25 from the ontology (and from the model)

**Comment by pierrechoffe** [comment]
@pasqLisena @rtroncy ok, removed from the list of properties (https://docs.google.com/spreadsheets/d/1RNhHnp4fWEhG8G4acx8FPi-nu9fUWNhc8JNf3SQwUFE/edit#gid=1401336326)
To be removed from protégé in next update ?

**Comment by pasqLisena** [comment]
Yes please :)

**Comment by pierrechoffe** [comment]
@pasqLisena I just saw that the DOREMUS classes and properties are based off the Documentation (which btw is *really* a wip, not up to date and not a reliable document). From a practical point of view, should I consider this doc as the entry point of our update, or should I work directly on protégé?

**Comment by rtroncy** [comment]
Done with commit https://github.com/DOREMUS-ANR/doremus-ontology/commit/31f3118f7ece3604716bf09441e75525782deb99
