### ISSUE TITLE
Inverse properties: how systematically should they be materialized?

### ISSUE THREAD

**Issue by pierrechoffe** [DOREMUS-ANR/doremus-ontology#2]
Based on a conversation with @rtroncy I did not create any inverse for the new properties, is it correct? If so, what about the other properties, should I delete all the inverse ?

**Comment by rtroncy** [comment]
I have never said that inverse properties should never be created. I just said that properties, in RDF, are oriented, and in their usage, are often used in just one direction. Some properties can be used in both ways, and in such a case, this is worth to materialize an inverse properties.

Rather than answering this issue in an abstract way, I suggest you bring the concrete cases where you think inverse properties should be or not be materialized in the ontology.

**Comment by pasqLisena** [comment]
>  If so, what about the other properties, should I delete all the inverse ?

On my opinion, the answer is **no**: some of that inverse properties are currently used in marc2rdf.

**Comment by pierrechoffe** [comment]
@rtroncy @pasqLisena ok, I can list some properties which **we** regularly use as inverse (e.g. P9i) but I see in the code that **you** use other properties as inverse which I would not have thought of (e.g. R17i_was_created_by), so it is difficult for me to say for sure whether we will ever use them or not. And as Pasquale said some inverse are currently in use in marc2rdf.
Is it a *problem* if I create inverses systematically then ? At least it would be consistent.

**Comment by rtroncy** [comment]
No, it is not a problem ... we can always later on query for the properties that are never instantiated, and delete them.

**Comment by pierrechoffe** [comment]
@pasqLisena just added inverse properties :)

**Comment by pasqLisena** [comment]
thank you Pierre 😄

**Comment by rtroncy** [comment]
Should we close this issue?

**Comment by pasqLisena** [comment]
yes
